# Generated by Django 4.2.7 on 2023-12-03 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_alter_contact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('Завод', 'Завод'), ('Розничная сеть', 'Розничная сеть'), ('Индивидуальный предприниматель', 'Индивидуальный предприниматель')], default='Завод', max_length=30, verbose_name='Звено')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('debt', models.DecimalField(decimal_places=2, max_digits=150, verbose_name='Задолженность')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.contact', verbose_name='Контакты')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Продукты')),
                ('sale_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель сети')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Сеть',
                'verbose_name_plural': 'Сети',
            },
        ),
    ]
